### ISSUE TITLE
New Coupon Code Management Dropdown Option

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#13]
Hi Mathew. We want to offer USRider (and others) an option of special 1 month free + 25% off membership. Please add this as an option in https://dressagetrainingonline.com/admin/site/addcouponmanagement Dropdown option "Type" so I can start preparing codes around it.

Please reply and let me know the timeline for when this can be add also so I can let USRider know and we can write the promotion around it.

Thank you much. -Angelea

**Comment by itekk** [comment]
Hi Angelea,
This is a big item to do. Coupon is used in many areas of the site. Also, a very good testing needs to be done in dev before we pushing it live. Since this is involved with the payment system we can afford to have any bugs in this area.

This is around 16 - 24 hrs work and can be completed in 1 week  to 10 days time.

Please confirm and i can start on it from tomorrow.

Thanks
Mathew

**Comment by dressagetrainingonline** [comment]
Thanks Mathew. Let's hold on this one right now. I started using the month free instead of the 10 day trial so we can get people using and invested in the site especially after Crystal from Member Concierge sets them up. We'll revisit at the end of this year. Thanks again! :)
